### ISSUE TITLE
Passing a non-breaking space as an attribute name raises a runtime error

### ISSUE THREAD

**Issue by magopian** [hecrj/html-parser#10]
Disclaimer: I believe the bug is in the compiler (see https://github.com/elm/html/issues/46 and https://github.com/elm/html/issues/47).

As it's likely not going to be fixed (for performance reasons), I guess it makes sense to fix it in this library.

To reproduce, try parsing and rendering something like `<img \u{00a0} />` (example in this [Ellie](https://ellie-app.com/5c8kffC7j2fa1)), and there will be a runtime error in the console: `InvalidCharacterError: String contains an invalid character`.

At least in some cases, this results in an infinite loop of rendering/runtime errors, which brings the browser (and the whole computer) to its knees.

**Comment by hecrj** [comment]
I see! Thanks for the detailed report and the fix! :tada: :tada:
