### ISSUE TITLE
expose Parser?

### ISSUE THREAD

**Issue by brandly** [hecrj/html-parser#6]
hey!

as mentioned [here](https://github.com/erkal/kite/issues/4#issuecomment-467639803), i wrote [a DOT parser](https://github.com/brandly/elm-dot-lang/blob/master/src/DotLang.elm). if you look at [the language spec](https://www.graphviz.org/doc/info/lang.html), an `ID` in DOT can be arbitrary HTML, allowing for cool graph renderings [like these](https://graphviz.gitlab.io/gallery/).

i'm under the impression that this package is the best elm 0.19 HTML parser, so i'd like to use it! if i were to use it, i think i need [this `node` definition](https://github.com/hecrj/html-parser/blob/1e9f6d3b19b736f66713a930ba9d6f9a1c060aea/src/Html/Parser.elm#L57-L63) which isn't exposed. ideally, i'd integrate it into [this `id` definition](https://github.com/brandly/elm-dot-lang/blob/4c3d0d362a4a8fa74329b53383cf94de578a384b/src/DotLang.elm#L310-L322).

is it unusual for parsers to expose the actual `Parser`? is there a way for me to leverage `run`? i don't know much about these things 😅 

thanks for your time

**Comment by hecrj** [comment]
You are right! I think it would be nice to expose `node` so other people can build their own parsers on top of it using `elm/parser`!

My only worry is exposing the `elm/parser` dependency directly. But given that it is an offical `elm` package I do not think it is a problem.

**Comment by brandly** [comment]
wow! thanks for responding so quickly. i'll grab the latest version and try to get it integrated ✌️

**Comment by hecrj** [comment]
Glad to help! Let me know if you have any issues! :)

**Comment by brandly** [comment]
[looks like it's working great!](https://github.com/brandly/elm-dot-lang/commit/835f3b809e7a3df71dc9b14f403fffcc76d0aca5)

i'm going to try a bunch of examples from [this gallery](https://graphviz.gitlab.io/gallery/) and make sure everything parses, but i'm under the impression that it can thoroughly parse DOT now.

thanks again!

**Comment by brandly** [comment]
hey 😄 

i noticed you have Travis CI working nicely on this repo. any idea what i'm doing wrong here? https://travis-ci.org/brandly/elm-dot-lang/builds/499480568

**Comment by hecrj** [comment]
This seems relevant: https://travis-ci.community/t/elm-test-fails-with-no-output-received-from-elm-make-when-searching-for-indirect-dependencies/2347

Try untracking your `package.json` and `package-lock.json` files and add those to `.gitignore`.
